cloud:
  aws:
    credentials:
      access-key: AKIA45VE3Q6POELRX2LF
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: xorpay

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

